name: Backend CI/CD with Tests and S3 Upload

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your AWS region

      - name: Initialize Terraform
        run: terraform init
        working-directory: IaC  # Change to your IaC directory

      - name: Run Python Tests
        run: python -m unittest discover -s tests -p 'test_func1.py'  # Modify as needed

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
        working-directory: IaC  # Change to your IaC directory

      - name: Apply Terraform Changes
        run: terraform apply tfplan
        working-directory: IaC  # Change to your IaC directory

      - name: Notify Success
        run: echo "Backend deployment successful"

      - name: Synchronize with S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Update with your AWS region
          SOURCE_DIR: 'IaC'  # Replace with the directory you want to sync

      - name: Cleanup
        run: rm IaC/tfplan

    # Additional options for notification, error handling, and more.
