name: Upload website to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your AWS region

      - name: Upload to S3
        run: |
          aws s3 sync aws-resume-challenge s3://${{ secrets.AWS_S3_BUCKET}} --delete --acl public-read
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Invalidate CloudFront Cache
        run: |
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id E2WESLV7EX1GFA --paths '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
